#!/bin/bash
# unit9 autograder helper script
# usage:
#     ./gradehelper-u09 username

[[ -z $1 ]] && exit 1
cd $1

main() {
  # Link and update the git repo
  ln -sv `pwd`/../../03/$1/* repo
  echo `pwd`/../../03/$1/* repo
  cd repo
  git stash
  git checkout master
  git pull
  git submodule init
  git submodule update --remote --merge

  # Check out the last commit before the due date.
  git checkout `git rev-list -n 1 --before="2015-03-19 08:00 -0700" master`

  # cd to unit09
  cd *nit*9 || cd src || cd *446/src || die "`ls`"
  # again, just in case there are more levels
  cd *nit*9 || echo ignoring error

  # open a shell
  bash
}


int_handler() {
  # kill rails
  killall -INT ruby; sleep 0.5
  killall -9 ruby

  exit
}

missing() {
  echo -e '\e[1;31m==> Missing requirement: '"$1"'\e[0m'
  #echo "`pwd` missing requirement: $1" >> /data/george/grading/csci446/05/log 
}

require() {
  echo -e '\e[1;34m==> requirement: '"$1"'\e[0m'
}

die() {
  echo Can\'t continue. :\(
  echo "$1"
  exit 1
}

israilsdir() {
  [[ -e app ]]
}

fixrake() {
  bundle install
  rake db:migrate || rake db:schema:load || (echo Rake won\'t run.; exit 1)
}

# Run
main $1 $2
